apiVersion: v1
kind: Service
metadata:
  labels:
    app: raj-hello-world
  name: raj-hello-world
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: raj-hello-world
  type: NodePort
